//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        public int PostID { get; set; }
        public string Foto { get; set; }
        public string Entrada { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Descript { get; set; }
        public string Located { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public byte[] ImageTest { get; set; }
        public string Image { get; set; }
    }
}
